services:
  db:
    container_name: econoplan-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - econoplan_data:/var/lib/postgresql/data

volumes:
  econoplan_data:
    external: true